import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css";

const poppins=Poppins({
  subsets:['latin'],  //Specifies the subset for the Poppins font, which here is latin, supporting Latin characters.
  weight:['100','200','300','400','500','600','700','800','900'],
  variable:'--font-poppins',  //Declares a CSS variable name, --font-poppins, which you can use in your stylesheets to apply this font.
})

export const metadata: Metadata = {
  title: "Doc-Drive",
  description: "Generated by create next app \n Developer: Ashwani Kumar Om",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
